<div class="ms-content-wrapper">
    <span class="has-icon"> <i class="flaticon-share"></i> </span>
    <span class="has-icon"> <i class="flaticon-security"></i> </span>
    <span class="has-icon"> <i class="flaticon-reader"></i> </span>
    <span class="has-icon"> <i class="flaticon-gear"></i> </span>
    <span class="has-icon"> <i class="flaticon-placeholder"></i> </span>
    <span class="has-icon"> <i class="flaticon-browser"></i> </span>
    <span class="has-icon"> <i class="flaticon-user"></i> </span>
    <span class="has-icon"> <i class="flaticon-mail"></i> </span>
    <span class="has-icon"> <i class="flaticon-shut-down"></i> </span>
    <span class="has-icon"> <i class="flaticon-bell"></i> </span>
    <span class="has-icon"> <i class="flaticon-statistics"></i> </span>
    <span class="has-icon"> <i class="flaticon-spreadsheet"></i> </span>
    <span class="has-icon"> <i class="flaticon-question"></i> </span>
    <span class="has-icon"> <i class="flaticon-chat"></i> </span>
    <span class="has-icon"> <i class="flaticon-phone"></i> </span>
    <span class="has-icon"> <i class="flaticon-browser-1"></i> </span>
    <span class="has-icon"> <i class="flaticon-layers"></i> </span>
    <span class="has-icon"> <i class="flaticon-grid"></i> </span>
    <span class="has-icon"> <i class="flaticon-hammer"></i> </span>
    <span class="has-icon"> <i class="flaticon-dashboard"></i> </span>
    <span class="has-icon"> <i class="flaticon-art"></i> </span>
    <span class="has-icon"> <i class="flaticon-list"></i> </span>
    <span class="has-icon"> <i class="flaticon-control"></i> </span>
    <span class="has-icon"> <i class="flaticon-alert"></i> </span>
    <span class="has-icon"> <i class="flaticon-alert-1"></i> </span>
    <span class="has-icon"> <i class="flaticon-toxic"></i> </span>
    <span class="has-icon"> <i class="flaticon-diamond"></i> </span>
    <span class="has-icon"> <i class="flaticon-star"></i> </span>
    <span class="has-icon"> <i class="flaticon-share-1"></i> </span>
    <span class="has-icon"> <i class="flaticon-search"></i> </span>
    <span class="has-icon"> <i class="flaticon-internet"></i> </span>
    <span class="has-icon"> <i class="flaticon-paint"></i> </span>
    <span class="has-icon"> <i class="flaticon-pie-chart"></i> </span>
    <span class="has-icon"> <i class="flaticon-pencil"></i> </span>
    <span class="has-icon"> <i class="flaticon-trash"></i> </span>
    <span class="has-icon"> <i class="flaticon-excel"></i> </span>
    <span class="has-icon"> <i class="flaticon-pdf"></i> </span>
    <span class="has-icon"> <i class="flaticon-network"></i> </span>
    <span class="has-icon"> <i class="flaticon-sticky-note"></i> </span>
    <span class="has-icon"> <i class="flaticon-alarm"></i> </span>
    <span class="has-icon"> <i class="flaticon-archive"></i> </span>
    <span class="has-icon"> <i class="flaticon-email"></i> </span>
    <span class="has-icon"> <i class="flaticon-stats"></i> </span>
    <span class="has-icon"> <i class="flaticon-conversation"></i> </span>
    <span class="has-icon"> <i class="flaticon-start"></i> </span>
    <span class="has-icon"> <i class="flaticon-tick-inside-circle"></i> </span>
    <span class="has-icon"> <i class="flaticon-information"></i> </span>
    <span class="has-icon"> <i class="flaticon-turn-notifications-off-button"></i> </span>
    <span class="has-icon"> <i class="flaticon-reuse"></i> </span>
    <span class="has-icon"> <i class="flaticon-secure-shield"></i> </span>
    <span class="has-icon"> <i class="flaticon-horn"></i> </span>
    <span class="has-icon"> <i class="flaticon-supermarket"></i> </span>
    <span class="has-icon"> <i class="flaticon-computer"></i> </span>
    <span class="has-icon"> <i class="flaticon-like"></i> </span>
    <span class="has-icon"> <i class="flaticon-speech-bubble"></i> </span>
    <span class="has-icon"> <i class="flaticon-paper-plane"></i> </span>
    <span class="has-icon"> <i class="flaticon-menu"></i> </span>
</div>